# Cálculo de la tasa de incidencia y el cambio porcentual y número de casos por cantón

In [38]:
import pandas as pd
import numpy as np

In [21]:
casos = pd.read_csv("../data/cases_dengue_rr.csv")
pob = pd.read_csv("../data/pob_int_rr.csv")

In [ ]:
casos.drop(["0", "1", "2", "3", "4", "5", "6", "7", "99", "98"], axis = 1, inplace= True)

In [23]:
pob.drop(["Unnamed: 0", "  0", "612", "613"], axis = 1, inplace= True)

In [28]:
pob = pob.rename({"week": "semana"}, axis = 1)

# Tasa de incidencia

  $$\text{Tasa de Incidencia} = \left( \frac{\text{Casos Nuevos de Dengue en la Semana } w}{\text{Población Total en el Cantón } c} \right) \times 100,000$$

In [58]:
casos_idx = casos.set_index('semana')
pob_idx = pob.set_index('semana')

In [30]:
incidencia = (casos_idx / pob_idx) * 100000

In [31]:
incidencia.head()

,101,102,103,104,105,106,107,108,109,110,...,608,609,610,611,701,702,703,704,705,706
semana,,,,,,,,,,,,,,,,,,,,,
2020-1,0.861606,0.0,2.506569,0.000000,0.0,1.619010,10.582323,0.000000,1.678326,4.295372,...,0.000000,0.000000,3.841168,0.000000,3.213778,12.701411,21.082941,11.582905,2.259072,16.221332
2020-2,3.159055,0.0,2.088611,2.608397,0.0,4.856663,10.581665,0.727744,1.678059,4.294625,...,0.000000,4.764986,3.840783,3.887507,5.356495,16.709538,14.055454,6.947989,4.517627,16.217601
2020-3,4.307576,0.0,1.253048,0.000000,0.0,1.618766,3.527002,0.000000,1.677793,0.000000,...,2.747843,0.000000,3.840397,7.771632,0.000000,10.692284,5.270855,2.315412,4.517111,23.420039
2020-4,2.010096,0.0,0.835287,10.431702,0.0,0.000000,7.053566,0.000000,3.355053,0.000000,...,0.000000,0.000000,15.360049,3.884127,4.285513,6.013386,12.298803,6.944482,4.516595,9.005637
2020-5,0.000000,0.0,1.670417,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.073096,...,0.000000,9.522579,5.759441,0.000000,4.285672,8.684524,28.111870,2.314244,0.000000,18.007135

In [ ]:
incidencia.to_csv("../data/incidencia.csv")

# Cambio porcentual y número de casos por cantón

$$\Delta\% = \left( \frac{\text{Casos en la Semana } w - \text{Casos en la Semana } w-1}{\text{Casos en la Semana } w-1} \right) \times 100$$

In [ ]:
cambio =  pd.DataFrame(np.where((casos_idx.shift(1) == 0) & (casos_idx == 0), 0, casos_idx.pct_change() * 100 ), index=casos_idx.index, columns=casos_idx.columns)
cambio = cambio.replace([np.inf, -np.inf], np.nan)
cambio = cambio.iloc[1:cambio.shape[0], 0:cambio.shape[1]]

In [ ]:
cambio.to_csv("../data/cambio.csv")

,101,102,103,104,105,106,107,108,109,110,...,608,609,610,611,701,702,703,704,705,706
semana,,,,,,,,,,,,,,,,,,,,,
2020-2,266.666667,0.0,-16.666667,NaN,0.0,200.000000,0.000000,NaN,0.000000,0.000000,...,0.0,NaN,0.000000,NaN,66.666667,31.578947,-33.333333,-40.000000,100.0,0.000000
2020-3,36.363636,0.0,-40.000000,-100.0,0.0,-66.666667,-66.666667,-100.0,0.000000,-100.000000,...,NaN,-100.0,0.000000,100.000000,-100.000000,-36.000000,-62.500000,-66.666667,0.0,44.444444
2020-4,-53.333333,0.0,-33.333333,NaN,0.0,-100.000000,100.000000,0.0,100.000000,0.000000,...,-100.0,0.0,300.000000,-50.000000,NaN,-43.750000,133.333333,200.000000,0.0,-61.538462
2020-5,-100.000000,0.0,100.000000,-100.0,0.0,0.000000,-100.000000,0.0,-100.000000,NaN,...,0.0,NaN,-62.500000,-100.000000,0.000000,44.444444,128.571429,-66.666667,-100.0,100.000000
2020-6,NaN,0.0,0.000000,NaN,0.0,NaN,0.000000,0.0,NaN,0.000000,...,0.0,-100.0,66.666667,NaN,-50.000000,-38.461538,-18.750000,500.000000,NaN,-50.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-48,-45.454545,100.0,0.000000,0.0,NaN,0.000000,-100.000000,-100.0,-28.571429,-83.333333,...,0.0,-100.0,-100.000000,50.000000,-50.000000,-40.000000,0.000000,-100.000000,-100.0,-50.000000
2025-49,29.166667,50.0,200.000000,0.0,-100.0,0.000000,0.000000,NaN,-20.000000,200.000000,...,0.0,0.0,NaN,-33.333333,-50.000000,33.333333,0.000000,0.000000,NaN,0.000000
2025-50,16.129032,-100.0,-33.333333,0.0,0.0,0.000000,0.000000,-100.0,75.000000,-33.333333,...,0.0,0.0,-100.000000,0.000000,0.000000,175.000000,100.000000,NaN,300.0,-100.000000
2025-51,-19.444444,0.0,-100.000000,0.0,0.0,-100.000000,0.000000,NaN,-14.285714,300.000000,...,0.0,NaN,0.000000,-50.000000,100.000000,-100.000000,-50.000000,-25.000000,-50.0,0.000000
2025-52,-82.758621,0.0,NaN,0.0,0.0,NaN,NaN,-100.0,-100.000000,-25.000000,...,0.0,200.0,NaN,500.000000,50.000000,0.000000,-100.000000,-66.666667,-100.0,0.000000